# Generated by Django 4.2.7 on 2026-03-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessmentid', models.AutoField(db_column='AssessmentID', primary_key=True, serialize=False)),
                ('assessmentname', models.CharField(db_column='AssessmentName', max_length=100)),
                ('assessmenttype', models.CharField(db_column='AssessmentType', max_length=10)),
                ('maxscore', models.DecimalField(db_column='MaxScore', decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(blank=True, db_column='Weight', decimal_places=2, max_digits=5, null=True)),
                ('duedate', models.DateField(db_column='DueDate')),
            ],
            options={
                'db_table': 'assessment',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(db_column='CourseID', primary_key=True, serialize=False)),
                ('coursecode', models.CharField(db_column='CourseCode', max_length=20, unique=True)),
                ('coursename', models.CharField(db_column='CourseName', max_length=100)),
                ('credits', models.IntegerField(db_column='Credits')),
                ('departmentid', models.IntegerField(db_column='DepartmentID')),
                ('description', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.AutoField(db_column='DepartmentID', primary_key=True, serialize=False)),
                ('departmentname', models.CharField(db_column='DepartmentName', max_length=100)),
                ('facultyid', models.IntegerField(db_column='FacultyID')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyid', models.AutoField(db_column='FacultyID', primary_key=True, serialize=False)),
                ('facultyname', models.CharField(db_column='FacultyName', max_length=100)),
                ('deanid', models.IntegerField(blank=True, db_column='DeanID', null=True)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecturerid', models.AutoField(db_column='LecturerID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('departmentid', models.IntegerField(db_column='DepartmentID')),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
            ],
            options={
                'db_table': 'lecture',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(db_column='StudentID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('dateofbirth', models.DateField(db_column='DateOfBirth')),
                ('enrollmentdate', models.DateField(db_column='EnrollmentDate')),
                ('departmentid', models.IntegerField(db_column='DepartmentID')),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gradeid', models.AutoField(db_column='GradeID', primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, db_column='Score', decimal_places=2, max_digits=5, null=True)),
                ('lettergrade', models.CharField(blank=True, db_column='LetterGrade', max_length=2, null=True)),
                ('submissiondate', models.DateTimeField(blank=True, db_column='SubmissionDate', null=True)),
                ('assessmentid', models.ForeignKey(db_column='AssessmentID', on_delete=django.db.models.deletion.DO_NOTHING, to='grades.assessment')),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.DO_NOTHING, to='grades.student')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollmentid', models.AutoField(db_column='EnrollmentID', primary_key=True, serialize=False)),
                ('enrollmentdate', models.DateField(db_column='EnrollmentDate')),
                ('semester', models.CharField(db_column='Semester', max_length=20)),
                ('status', models.CharField(db_column='Status', max_length=9)),
                ('courseid', models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.DO_NOTHING, to='grades.course')),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.DO_NOTHING, to='grades.student')),
            ],
            options={
                'db_table': 'enrollment',
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='courseid',
            field=models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.DO_NOTHING, to='grades.course'),
        ),
    ]
