# Generated by Django 4.2.7 on 2026-05-03 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='class_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='flagged_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='flagged_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved by HOD'), ('rejected', 'Rejected by HOD'), ('final', 'Final Approved')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='was_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('hod', 'Head of Department'), ('dean', 'Dean'), ('admin', 'Admin')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('assignmentid', models.AutoField(db_column='AssignmentID', primary_key=True, serialize=False)),
                ('semesterid', models.IntegerField(db_column='SemesterID')),
                ('courseid', models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.DO_NOTHING, to='grades.course')),
                ('lecturerid', models.ForeignKey(db_column='LecturerID', on_delete=django.db.models.deletion.DO_NOTHING, to='grades.lecture')),
            ],
            options={
                'db_table': 'course_assignment',
            },
        ),
    ]
