# Generated by Django 4.2.7 on 2026-03-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='class_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='flagged_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='flagged_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Reason if overriding AI warning', null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='was_flagged',
            field=models.BooleanField(default=False, help_text='Was this grade flagged by AI?'),
        ),
    ]
