# Generated by Django 4.2.7 on 2026-04-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_add_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('assignmentid', models.AutoField(db_column='AssignmentID', primary_key=True, serialize=False)),
                ('semesterid', models.IntegerField(db_column='SemesterID')),
                ('courseid', models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.DO_NOTHING, to='grades.course')),
                ('lecturerid', models.ForeignKey(db_column='LecturerID', on_delete=django.db.models.deletion.DO_NOTHING, to='grades.lecture')),
            ],
            options={
                'db_table': 'course_assignment',
            },
        ),
    ]
