# Generated by Django 4.2.7 on 2026-05-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_student_number_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseassignment',
            name='portal_is_open',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='portal_updated_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='hod_comment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentnumber',
        ),
    ]
