# Generated by Django 4.2.7 on 2026-05-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_remove_courseassignment_portal_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(db_column='Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='email',
            field=models.CharField(db_column='Email', max_length=100),
        ),
    ]
